### PR TITLE
style: ESLint with Prettier

### PR DESCRIPTION
**Pull request by Anush008**
ESLint aur Prettier lagaya hain. `lint` nam ka ek build script bhi.

`npm run lint` karna. Bahut linting errors hain abhi bhi.

https://github.com/MaxAnii/SENTRY/pull/1/commits/f885aba8e340f394f9f943a531c9813164eba226, https://github.com/MaxAnii/SENTRY/pull/1/commits/5341411c1869aa7415f2db439ccd3fe4df182d04 - DevDeps pe move kardiya hain. Bundle size kam karne ke liye.

Unused deps prune ki hain

### CODE REVIEW

**Comment by Anush008** [comment]
@MaxAnii, https://github.com/MaxAnii/SENTRY/pull/1/commits/66c83ba44369a457b622bd8c88cb4c351ba4a59a ye sab kyun daale thhe lekin?

**Comment by MaxAnii** [comment]
@Anush008 pata nhi kab hui itni sari dependences install 👉👈

**Comment by Anush008** [comment]
@MaxAnii, `npm run lint` karna. Kuch linting errors bhi hain.

**Comment by MaxAnii** [comment]
Ruk filhaal to app hi crash ho giya hai 😢

**Comment by Anush008** [comment]
Koi required dep udd gaya kya?
💀

**Comment by MaxAnii** [comment]
Nhi hogiya thk.

**Comment by Anush008** [comment]
Try this.
https://github.com/MaxAnii/SENTRY/pull/1#issuecomment-2016429093

**Comment by MaxAnii** [comment]
Haan karunga

**Pull request merged**
